/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Team } from "./types";

export const TEAMS_DATABASE: Team[] = [
  {
    id: "mancity",
    name: "Manchester City",
    shortName: "MCI",
    logo: "⚽",
    color: "#00b2ff", // Sky Blue
    secondaryColor: "#ffffff",
    defaultAttackXg: 2.4,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 85,
    defaultH2hAverageGoals: 3.2,
    formHistory: [70, 75, 78, 80, 85, 82, 80, 85, 90, 85],
  },
  {
    id: "realmadrid",
    name: "Real Madrid",
    shortName: "RMA",
    logo: "🔱",
    color: "#eab308", // Golden Yellow
    secondaryColor: "#e6a200", 
    defaultAttackXg: 2.2,
    defaultDefenseXgConceded: 0.8,
    defaultForm: 88,
    defaultH2hAverageGoals: 2.9,
    formHistory: [82, 85, 84, 88, 92, 90, 88, 92, 85, 88],
  },
  {
    id: "liverpool",
    name: "Liverpool",
    shortName: "LIV",
    logo: "🦅",
    color: "#ef4444", // Bright Red
    secondaryColor: "#f6eb61", 
    defaultAttackXg: 2.3,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 82,
    defaultH2hAverageGoals: 3.1,
    formHistory: [75, 78, 80, 78, 82, 85, 84, 80, 85, 82],
  },
  {
    id: "arsenal",
    name: "Arsenal",
    shortName: "ARS",
    logo: "🔴",
    color: "#f87171", // Soft Red
    secondaryColor: "#ffffff",
    defaultAttackXg: 2.1,
    defaultDefenseXgConceded: 0.9,
    defaultForm: 80,
    defaultH2hAverageGoals: 2.8,
    formHistory: [70, 74, 76, 78, 80, 82, 85, 80, 78, 80],
  },
  {
    id: "bayern",
    name: "Bayern Munich",
    shortName: "FCB",
    logo: "🛡️",
    color: "#ea580c", // Orange-Red
    secondaryColor: "#0066b2", 
    defaultAttackXg: 2.3,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 75,
    defaultH2hAverageGoals: 3.4,
    formHistory: [80, 78, 75, 72, 70, 74, 75, 78, 72, 75],
  },
  {
    id: "barcelona",
    name: "FC Barcelona",
    shortName: "BAR",
    logo: "🔵",
    color: "#3b82f6", // Blue
    secondaryColor: "#a50044", 
    defaultAttackXg: 1.9,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 70,
    defaultH2hAverageGoals: 2.7,
    formHistory: [65, 62, 68, 70, 72, 75, 70, 68, 72, 70],
  },
  {
    id: "psg",
    name: "Paris Saint-Germain",
    shortName: "PSG",
    logo: "🗼",
    color: "#1e40af", // Deep Blue
    secondaryColor: "#da291c", 
    defaultAttackXg: 2.0,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 78,
    defaultH2hAverageGoals: 3.0,
    formHistory: [85, 82, 80, 78, 75, 78, 80, 76, 75, 78],
  },
  {
    id: "inter",
    name: "Inter Milan",
    shortName: "INT",
    logo: "🐍",
    color: "#0284c7", // Sky/Blue
    secondaryColor: "#000000", 
    defaultAttackXg: 1.9,
    defaultDefenseXgConceded: 0.7,
    defaultForm: 84,
    defaultH2hAverageGoals: 2.4,
    formHistory: [80, 82, 85, 84, 86, 88, 85, 82, 85, 84],
  },
  {
    id: "leverkusen",
    name: "Bayer Leverkusen",
    shortName: "B04",
    logo: "🦁",
    color: "#475569", // Cool Grey / Dark
    secondaryColor: "#e32219", 
    defaultAttackXg: 2.1,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 80,
    defaultH2hAverageGoals: 2.9,
    formHistory: [90, 88, 85, 82, 80, 78, 82, 85, 80, 80],
  },
  {
    id: "dortmund",
    name: "Borussia Dortmund",
    shortName: "BVB",
    logo: "🐝",
    color: "#eab308", // Yellow
    secondaryColor: "#000000",
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 1.4,
    defaultForm: 65,
    defaultH2hAverageGoals: 3.3,
    formHistory: [55, 60, 58, 62, 65, 68, 70, 62, 60, 65],
  },
  {
    id: "juventus",
    name: "Juventus",
    shortName: "JUV",
    logo: "🦓",
    color: "#64748b", // Slate
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 0.8,
    defaultForm: 72,
    defaultH2hAverageGoals: 2.1,
    formHistory: [65, 68, 70, 72, 74, 70, 72, 75, 70, 72],
  },
  {
    id: "chelsea",
    name: "Chelsea",
    shortName: "CHE",
    logo: "🦁",
    color: "#2563eb", // Royal blue
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 1.4,
    defaultForm: 65,
    defaultH2hAverageGoals: 2.8,
    formHistory: [50, 55, 60, 58, 62, 64, 65, 68, 62, 65],
  },
  {
    id: "manunited",
    name: "Manchester United",
    shortName: "MUN",
    logo: "👿",
    color: "#dc2626", // Red-600
    secondaryColor: "#ffe500", 
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.5,
    defaultForm: 60,
    defaultH2hAverageGoals: 2.6,
    formHistory: [45, 50, 55, 52, 58, 60, 62, 55, 58, 60],
  },
  {
    id: "tottenham",
    name: "Tottenham Hotspur",
    shortName: "TOT",
    logo: "🐓",
    color: "#1e3a8a", // Dark navy
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.9,
    defaultDefenseXgConceded: 1.6,
    defaultForm: 64,
    defaultH2hAverageGoals: 3.4,
    formHistory: [70, 68, 65, 62, 60, 62, 65, 68, 60, 64],
  },
  {
    id: "atletico",
    name: "Atlético Madrid",
    shortName: "ATM",
    logo: "🐻",
    color: "#ea2c1c", // Atletico Red
    secondaryColor: "#202c65", 
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 70,
    defaultH2hAverageGoals: 2.3,
    formHistory: [75, 72, 70, 68, 70, 72, 75, 68, 72, 70],
  },
  {
    id: "acmilan",
    name: "AC Milan",
    shortName: "MIL",
    logo: "😈",
    color: "#991b1b", // Deep red
    secondaryColor: "#000000", 
    defaultAttackXg: 1.7,
    defaultDefenseXgConceded: 1.3,
    defaultForm: 68,
    defaultH2hAverageGoals: 2.6,
    formHistory: [60, 62, 65, 64, 68, 70, 72, 65, 66, 68],
  },
  {
    id: "astonvilla",
    name: "Aston Villa",
    shortName: "AVL",
    logo: "🦁",
    color: "#7a263a", // Claret
    secondaryColor: "#95bfe5", // Sky Blue
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 1.3,
    defaultForm: 75,
    defaultH2hAverageGoals: 2.8,
    formHistory: [70, 72, 75, 78, 80, 74, 76, 78, 72, 75],
    category: "club",
  },
  {
    id: "newcastle",
    name: "Newcastle United",
    shortName: "NEW",
    logo: "🦓",
    color: "#111827", // Black
    secondaryColor: "#ffffff", // White
    defaultAttackXg: 1.9,
    defaultDefenseXgConceded: 1.3,
    defaultForm: 74,
    defaultH2hAverageGoals: 3.0,
    formHistory: [72, 70, 74, 76, 75, 78, 80, 72, 70, 74],
    category: "club",
  },
  {
    id: "westham",
    name: "West Ham United",
    shortName: "WHU",
    logo: "⚒️",
    color: "#7a263a", // Claret
    secondaryColor: "#00b2ff", // Sky Blue
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.4,
    defaultForm: 68,
    defaultH2hAverageGoals: 2.9,
    formHistory: [60, 62, 65, 68, 70, 72, 68, 65, 70, 68],
    category: "club",
  },
  {
    id: "brighton",
    name: "Brighton & Hove Albion",
    shortName: "BHA",
    logo: "🕊️",
    color: "#1d4ed8", // Blue
    secondaryColor: "#ffffff", // White
    defaultAttackXg: 1.7,
    defaultDefenseXgConceded: 1.3,
    defaultForm: 72,
    defaultH2hAverageGoals: 3.0,
    formHistory: [65, 68, 70, 72, 75, 70, 68, 74, 72, 72],
    category: "club",
  },
  {
    id: "crystalpalace",
    name: "Crystal Palace",
    shortName: "CRY",
    logo: "🔮",
    color: "#1e3a8a", // Blue
    secondaryColor: "#dc2626", // Red
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 1.3,
    defaultForm: 66,
    defaultH2hAverageGoals: 2.6,
    formHistory: [60, 62, 64, 65, 68, 70, 66, 62, 65, 66],
    category: "club",
  },
  {
    id: "everton",
    name: "Everton",
    shortName: "EVE",
    logo: "🔵",
    color: "#1d4ed8", // Royal Blue
    secondaryColor: "#ffffff", // White
    defaultAttackXg: 1.4,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 65,
    defaultH2hAverageGoals: 2.3,
    formHistory: [55, 58, 60, 62, 65, 68, 64, 60, 62, 65],
    category: "club",
  },
  {
    id: "fulham",
    name: "Fulham",
    shortName: "FUL",
    logo: "⚪",
    color: "#ffffff", // White
    secondaryColor: "#000000", // Black
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 1.3,
    defaultForm: 69,
    defaultH2hAverageGoals: 2.6,
    formHistory: [62, 65, 68, 70, 72, 68, 65, 70, 68, 69],
    category: "club",
  },
  {
    id: "bournemouth",
    name: "Bournemouth",
    shortName: "BOU",
    logo: "🍒",
    color: "#b91c1c", // Red / Black
    secondaryColor: "#000000", // Black
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.4,
    defaultForm: 70,
    defaultH2hAverageGoals: 3.1,
    formHistory: [60, 62, 65, 68, 72, 70, 68, 74, 70, 70],
    category: "club",
  },
  {
    id: "wolves",
    name: "Wolverhampton Wanderers",
    shortName: "WOL",
    logo: "🐺",
    color: "#f59e0b", // Gold
    secondaryColor: "#000000", // Black
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 1.5,
    defaultForm: 63,
    defaultH2hAverageGoals: 2.7,
    formHistory: [50, 52, 55, 58, 60, 62, 65, 60, 58, 63],
    category: "club",
  },
  {
    id: "brentford",
    name: "Brentford",
    shortName: "BRE",
    logo: "🐝",
    color: "#e11d48", // Red
    secondaryColor: "#ffffff", // White
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 1.5,
    defaultForm: 64,
    defaultH2hAverageGoals: 3.0,
    formHistory: [55, 58, 60, 62, 65, 63, 60, 66, 62, 64],
    category: "club",
  },
  {
    id: "nottinghamforest",
    name: "Nottingham Forest",
    shortName: "NFO",
    logo: "🌳",
    color: "#dc2626", // Forest Red
    secondaryColor: "#ffffff", // White
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 1.3,
    defaultForm: 68,
    defaultH2hAverageGoals: 2.6,
    formHistory: [60, 62, 65, 68, 70, 66, 65, 72, 68, 68],
    category: "club",
  },
  {
    id: "leicester",
    name: "Leicester City",
    shortName: "LEI",
    logo: "🦊",
    color: "#1e3a8a", // Royal Blue
    secondaryColor: "#facc15", // Yellow
    defaultAttackXg: 1.4,
    defaultDefenseXgConceded: 1.5,
    defaultForm: 62,
    defaultH2hAverageGoals: 2.7,
    formHistory: [50, 53, 55, 58, 60, 62, 65, 58, 60, 62],
    category: "club",
  },
  {
    id: "ipswich",
    name: "Ipswich Town",
    shortName: "IPS",
    logo: "🚜",
    color: "#1d4ed8", // Blue
    secondaryColor: "#ffffff", // White
    defaultAttackXg: 1.3,
    defaultDefenseXgConceded: 1.6,
    defaultForm: 60,
    defaultH2hAverageGoals: 2.8,
    formHistory: [45, 50, 52, 55, 58, 60, 56, 52, 58, 60],
    category: "club",
  },
  {
    id: "southampton",
    name: "Southampton",
    shortName: "SOU",
    logo: "🔴",
    color: "#dc2626", // Red
    secondaryColor: "#ffffff", // White
    defaultAttackXg: 1.3,
    defaultDefenseXgConceded: 1.6,
    defaultForm: 58,
    defaultH2hAverageGoals: 2.7,
    formHistory: [40, 45, 50, 52, 55, 58, 54, 50, 56, 58],
    category: "club",
  },
  {
    id: "argentina",
    name: "Argentina",
    shortName: "ARG",
    logo: "🇦🇷",
    color: "#75aadb", // Sky Blue
    secondaryColor: "#ffffff",
    defaultAttackXg: 2.1,
    defaultDefenseXgConceded: 0.7,
    defaultForm: 92,
    defaultH2hAverageGoals: 2.5,
    formHistory: [85, 88, 90, 85, 92, 94, 95, 90, 92, 92],
    category: "national",
  },
  {
    id: "brazil",
    name: "Brazil",
    shortName: "BRA",
    logo: "🇧🇷",
    color: "#eab308", // Yellow
    secondaryColor: "#15803d", // Green
    defaultAttackXg: 2.3,
    defaultDefenseXgConceded: 0.9,
    defaultForm: 80,
    defaultH2hAverageGoals: 2.8,
    formHistory: [70, 75, 78, 72, 80, 82, 85, 78, 82, 80],
    category: "national",
  },
  {
    id: "france",
    name: "France",
    shortName: "FRA",
    logo: "🇫🇷",
    color: "#1e3a8a", // Blue
    secondaryColor: "#ef4444", // Red
    defaultAttackXg: 2.2,
    defaultDefenseXgConceded: 0.8,
    defaultForm: 84,
    defaultH2hAverageGoals: 2.7,
    formHistory: [80, 82, 82, 85, 88, 84, 85, 80, 85, 84],
    category: "national",
  },
  {
    id: "germany",
    name: "Germany",
    shortName: "GER",
    logo: "🇩🇪",
    color: "#1e293b", // Slate Black
    secondaryColor: "#facc15", // Gold
    defaultAttackXg: 1.9,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 76,
    defaultH2hAverageGoals: 3.1,
    formHistory: [68, 70, 72, 75, 74, 78, 80, 75, 72, 76],
    category: "national",
  },
  {
    id: "spain",
    name: "Spain",
    shortName: "ESP",
    logo: "🇪🇸",
    color: "#dc2626", // Red
    secondaryColor: "#eab308", // Yellow
    defaultAttackXg: 2.0,
    defaultDefenseXgConceded: 0.8,
    defaultForm: 86,
    defaultH2hAverageGoals: 2.6,
    formHistory: [75, 78, 80, 82, 85, 88, 90, 85, 84, 86],
    category: "national",
  },
  {
    id: "england",
    name: "England",
    shortName: "ENG",
    logo: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    color: "#ffffff", // Pure White
    secondaryColor: "#b91c1c", // Red
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 0.9,
    defaultForm: 78,
    defaultH2hAverageGoals: 2.4,
    formHistory: [70, 72, 75, 78, 80, 82, 78, 75, 80, 78],
    category: "national",
  },
  {
    id: "portugal",
    name: "Portugal",
    shortName: "POR",
    logo: "🇵🇹",
    color: "#dc2626", // Red
    secondaryColor: "#16a34a", // Green
    defaultAttackXg: 2.1,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 82,
    defaultH2hAverageGoals: 2.9,
    formHistory: [78, 80, 82, 85, 80, 82, 85, 84, 80, 82],
    category: "national",
  },
  {
    id: "morocco",
    name: "Morocco",
    shortName: "MAR",
    logo: "🇲🇦",
    color: "#0f766e", // Teal
    secondaryColor: "#be123c", // Ruby Red
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 0.7,
    defaultForm: 75,
    defaultH2hAverageGoals: 1.9,
    formHistory: [72, 70, 74, 75, 78, 76, 75, 72, 78, 75],
    category: "national",
  },
  {
    id: "usa",
    name: "United States",
    shortName: "USA",
    logo: "🇺🇸",
    color: "#1e3a8a", // Navy Blue
    secondaryColor: "#ef4444", // Red
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 78,
    defaultH2hAverageGoals: 2.6,
    formHistory: [74, 76, 72, 75, 80, 78, 76, 74, 82, 78],
    category: "national",
  },
  {
    id: "mexico",
    name: "Mexico",
    shortName: "MEX",
    logo: "🇲🇽",
    color: "#15803d", // Green
    secondaryColor: "#dc2626", // Red
    defaultAttackXg: 1.7,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 74,
    defaultH2hAverageGoals: 2.5,
    formHistory: [70, 72, 68, 74, 76, 72, 70, 75, 72, 74],
    category: "national",
  },
  {
    id: "canada",
    name: "Canada",
    shortName: "CAN",
    logo: "🇨🇦",
    color: "#dc2626", // Red
    secondaryColor: "#ffffff", // White
    defaultAttackXg: 1.7,
    defaultDefenseXgConceded: 1.3,
    defaultForm: 72,
    defaultH2hAverageGoals: 2.7,
    formHistory: [65, 68, 70, 72, 70, 75, 72, 68, 74, 72],
    category: "national",
  },
  {
    id: "italy",
    name: "Italy",
    shortName: "ITA",
    logo: "🇮🇹",
    color: "#1d4ed8", // Azzurri Blue
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 0.8,
    defaultForm: 82,
    defaultH2hAverageGoals: 2.2,
    formHistory: [78, 80, 84, 82, 85, 80, 78, 82, 84, 82],
    category: "national",
  },
  {
    id: "netherlands",
    name: "Netherlands",
    shortName: "NED",
    logo: "🇳🇱",
    color: "#f97316", // Oranje Orange
    secondaryColor: "#ffffff",
    defaultAttackXg: 2.1,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 83,
    defaultH2hAverageGoals: 3.0,
    formHistory: [75, 78, 82, 85, 80, 84, 86, 82, 85, 83],
    category: "national",
  },
  {
    id: "belgium",
    name: "Belgium",
    shortName: "BEL",
    logo: "🇧🇪",
    color: "#991b1b", // Red Devil
    secondaryColor: "#facc15", // yellow
    defaultAttackXg: 1.9,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 75,
    defaultH2hAverageGoals: 2.9,
    formHistory: [72, 70, 74, 76, 78, 74, 72, 75, 78, 75],
    category: "national",
  },
  {
    id: "croatia",
    name: "Croatia",
    shortName: "CRO",
    logo: "🇭🇷",
    color: "#dc2626", // Red checkered
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.7,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 79,
    defaultH2hAverageGoals: 2.4,
    formHistory: [75, 78, 80, 76, 74, 78, 82, 80, 78, 79],
    category: "national",
  },
  {
    id: "uruguay",
    name: "Uruguay",
    shortName: "URU",
    logo: "🇺🇾",
    color: "#38bdf8", // Sky Blue
    secondaryColor: "#ffffff",
    defaultAttackXg: 2.0,
    defaultDefenseXgConceded: 0.9,
    defaultForm: 85,
    defaultH2hAverageGoals: 2.6,
    formHistory: [80, 82, 85, 88, 84, 82, 85, 87, 83, 85],
    category: "national",
  },
  {
    id: "colombia",
    name: "Colombia",
    shortName: "COL",
    logo: "🇨🇴",
    color: "#eab308", // Yellow
    secondaryColor: "#1d4ed8", // Blue
    defaultAttackXg: 1.9,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 84,
    defaultH2hAverageGoals: 2.5,
    formHistory: [76, 78, 82, 85, 87, 84, 82, 86, 88, 84],
    category: "national",
  },
  {
    id: "japan",
    name: "Japan",
    shortName: "JPN",
    logo: "🇯🇵",
    color: "#1e3a8a", // Blue Samurai
    secondaryColor: "#ffffff",
    defaultAttackXg: 2.0,
    defaultDefenseXgConceded: 0.9,
    defaultForm: 86,
    defaultH2hAverageGoals: 2.8,
    formHistory: [80, 82, 85, 87, 90, 88, 84, 86, 88, 86],
    category: "national",
  },
  {
    id: "southkorea",
    name: "South Korea",
    shortName: "KOR",
    logo: "🇰🇷",
    color: "#dc2626", // Red Taeguk
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 78,
    defaultH2hAverageGoals: 2.7,
    formHistory: [70, 72, 76, 75, 78, 80, 82, 76, 78, 78],
    category: "national",
  },
  {
    id: "australia",
    name: "Australia",
    shortName: "AUS",
    logo: "🇦🇺",
    color: "#eab308", // Golden Wattle
    secondaryColor: "#15803d",
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 75,
    defaultH2hAverageGoals: 2.3,
    formHistory: [70, 72, 74, 76, 72, 75, 78, 74, 72, 75],
    category: "national",
  },
  {
    id: "senegal",
    name: "Senegal",
    shortName: "SEN",
    logo: "🇸🇳",
    color: "#15803d", // Green
    secondaryColor: "#dc2626", // Red
    defaultAttackXg: 1.7,
    defaultDefenseXgConceded: 0.9,
    defaultForm: 77,
    defaultH2hAverageGoals: 2.2,
    formHistory: [72, 74, 75, 78, 80, 76, 74, 78, 75, 77],
    category: "national",
  },
  {
    id: "switzerland",
    name: "Switzerland",
    shortName: "SUI",
    logo: "🇨🇭",
    color: "#dc2626", // Red
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 76,
    defaultH2hAverageGoals: 2.4,
    formHistory: [72, 70, 74, 76, 78, 75, 76, 78, 74, 76],
    category: "national",
  },
  {
    id: "denmark",
    name: "Denmark",
    shortName: "DEN",
    logo: "🇩🇰", // Danish Flag
    color: "#b91c1c", // Red
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.7,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 75,
    defaultH2hAverageGoals: 2.5,
    formHistory: [70, 72, 75, 78, 74, 72, 76, 75, 72, 75],
    category: "national",
  },
  {
    id: "saudiarabia",
    name: "Saudi Arabia",
    shortName: "KSA",
    logo: "🇸🇦",
    color: "#16a34a", // Green
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 1.3,
    defaultForm: 70,
    defaultH2hAverageGoals: 2.1,
    formHistory: [60, 62, 65, 68, 70, 72, 70, 68, 72, 70],
    category: "national",
  },
  {
    id: "austria",
    name: "Austria",
    shortName: "AUT",
    logo: "🇦🇹",
    color: "#dc2626", // Red
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 78,
    defaultH2hAverageGoals: 2.6,
    formHistory: [72, 74, 76, 80, 78, 75, 82, 78, 76, 78],
    category: "national",
  },
  {
    id: "bosnia",
    name: "Bosnia & Herzegovina",
    shortName: "BIH",
    logo: "🇧🇦",
    color: "#1d4ed8", // Blue
    secondaryColor: "#facc15", // yellow
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 72,
    defaultH2hAverageGoals: 2.4,
    formHistory: [65, 68, 70, 72, 74, 70, 68, 75, 72, 72],
    category: "national",
  },
  {
    id: "czechia",
    name: "Czechia",
    shortName: "CZE",
    logo: "🇨🇿",
    color: "#b91c1c", // Red
    secondaryColor: "#1d4ed8", // Blue
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 74,
    defaultH2hAverageGoals: 2.5,
    formHistory: [70, 72, 75, 72, 70, 76, 74, 72, 78, 74],
    category: "national",
  },
  {
    id: "norway",
    name: "Norway",
    shortName: "NOR",
    logo: "🇳🇴",
    color: "#e11d48", // Red
    secondaryColor: "#1e3a8a", // Navy
    defaultAttackXg: 1.9,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 76,
    defaultH2hAverageGoals: 2.9,
    formHistory: [70, 72, 74, 78, 80, 75, 72, 76, 78, 76],
    category: "national",
  },
  {
    id: "scotland",
    name: "Scotland",
    shortName: "SCO",
    logo: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    color: "#1e3a8a", // Navy
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 72,
    defaultH2hAverageGoals: 2.3,
    formHistory: [68, 70, 72, 75, 70, 68, 74, 72, 70, 72],
    category: "national",
  },
  {
    id: "sweden",
    name: "Sweden",
    shortName: "SWE",
    logo: "🇸🇪",
    color: "#eab308", // Yellow
    secondaryColor: "#1d4ed8", // Blue
    defaultAttackXg: 1.7,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 75,
    defaultH2hAverageGoals: 2.7,
    formHistory: [72, 70, 74, 76, 78, 75, 72, 78, 74, 75],
    category: "national",
  },
  {
    id: "turkiye",
    name: "Türkiye",
    shortName: "TUR",
    logo: "🇹🇷",
    color: "#dc2626", // Red
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 77,
    defaultH2hAverageGoals: 2.8,
    formHistory: [72, 75, 78, 74, 72, 80, 78, 75, 76, 77],
    category: "national",
  },
  {
    id: "ecuador",
    name: "Ecuador",
    shortName: "ECU",
    logo: "🇪🇨",
    color: "#facc15", // Yellow
    secondaryColor: "#1d4ed8", // Blue
    defaultAttackXg: 1.7,
    defaultDefenseXgConceded: 0.9,
    defaultForm: 79,
    defaultH2hAverageGoals: 2.4,
    formHistory: [75, 78, 80, 76, 78, 82, 80, 78, 82, 79],
    category: "national",
  },
  {
    id: "paraguay",
    name: "Paraguay",
    shortName: "PAR",
    logo: "🇵🇾",
    color: "#dc2626", // Red
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 0.9,
    defaultForm: 74,
    defaultH2hAverageGoals: 2.0,
    formHistory: [70, 72, 74, 70, 72, 76, 74, 72, 75, 74],
    category: "national",
  },
  {
    id: "iran",
    name: "IR Iran",
    shortName: "IRN",
    logo: "🇮🇷",
    color: "#16a34a", // Green
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 81,
    defaultH2hAverageGoals: 2.6,
    formHistory: [76, 78, 80, 82, 84, 80, 78, 82, 84, 81],
    category: "national",
  },
  {
    id: "iraq",
    name: "Iraq",
    shortName: "IRQ",
    logo: "🇮🇶",
    color: "#15803d", // Green
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 73,
    defaultH2hAverageGoals: 2.3,
    formHistory: [68, 70, 72, 75, 74, 72, 76, 72, 70, 73],
    category: "national",
  },
  {
    id: "jordan",
    name: "Jordan",
    shortName: "JOR",
    logo: "🇯🇴",
    color: "#dc2626", // Red
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 75,
    defaultH2hAverageGoals: 2.4,
    formHistory: [70, 72, 75, 78, 74, 72, 76, 75, 72, 75],
    category: "national",
  },
  {
    id: "qatar",
    name: "Qatar",
    shortName: "QAT",
    logo: "🇶🇦",
    color: "#991b1b", // Maroon
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.7,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 76,
    defaultH2hAverageGoals: 2.5,
    formHistory: [72, 74, 76, 78, 80, 75, 72, 76, 78, 76],
    category: "national",
  },
  {
    id: "uzbekistan",
    name: "Uzbekistan",
    shortName: "UZB",
    logo: "🇺🇿",
    color: "#3b82f6", // Blue
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 75,
    defaultH2hAverageGoals: 2.3,
    formHistory: [68, 70, 73, 75, 78, 74, 72, 76, 75, 75],
    category: "national",
  },
  {
    id: "algeria",
    name: "Algeria",
    shortName: "ALG",
    logo: "🇩🇿",
    color: "#15803d", // Green
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 78,
    defaultH2hAverageGoals: 2.5,
    formHistory: [74, 76, 78, 80, 76, 74, 80, 78, 75, 78],
    category: "national",
  },
  {
    id: "capeverde",
    name: "Cabo Verde",
    shortName: "CPV",
    logo: "🇨🇻",
    color: "#1e3a8a", // Navy
    secondaryColor: "#dc2626",
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 73,
    defaultH2hAverageGoals: 2.2,
    formHistory: [68, 70, 72, 74, 76, 72, 70, 75, 72, 73],
    category: "national",
  },
  {
    id: "congodr",
    name: "Congo DR",
    shortName: "COD",
    logo: "🇨🇩",
    color: "#3b82f6", // Blue
    secondaryColor: "#dc2626", // Red
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 74,
    defaultH2hAverageGoals: 2.3,
    formHistory: [70, 72, 74, 76, 72, 70, 75, 72, 76, 74],
    category: "national",
  },
  {
    id: "ivorycoast",
    name: "Côte d'Ivoire",
    shortName: "CIV",
    logo: "🇨🇮",
    color: "#f97316", // Orange
    secondaryColor: "#15803d", // Green
    defaultAttackXg: 1.8,
    defaultDefenseXgConceded: 0.9,
    defaultForm: 82,
    defaultH2hAverageGoals: 2.6,
    formHistory: [78, 80, 84, 86, 82, 80, 85, 83, 80, 82],
    category: "national",
  },
  {
    id: "egypt",
    name: "Egypt",
    shortName: "EGY",
    logo: "🇪🇬",
    color: "#dc2626", // Red
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.9,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 80,
    defaultH2hAverageGoals: 2.5,
    formHistory: [74, 76, 80, 82, 85, 80, 78, 82, 84, 80],
    category: "national",
  },
  {
    id: "ghana",
    name: "Ghana",
    shortName: "GHA",
    logo: "🇬🇭",
    color: "#ffffff", // White
    secondaryColor: "#000000",
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 73,
    defaultH2hAverageGoals: 2.4,
    formHistory: [68, 70, 72, 75, 74, 70, 72, 75, 71, 73],
    category: "national",
  },
  {
    id: "southafrica",
    name: "South Africa",
    shortName: "RSA",
    logo: "🇿🇦",
    color: "#eab308", // Yellow
    secondaryColor: "#15803d", // Green
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.0,
    defaultForm: 75,
    defaultH2hAverageGoals: 2.2,
    formHistory: [70, 72, 74, 76, 78, 74, 72, 76, 75, 75],
    category: "national",
  },
  {
    id: "tunisia",
    name: "Tunisia",
    shortName: "TUN",
    logo: "🇹🇳",
    color: "#dc2626", // Red
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 0.9,
    defaultForm: 74,
    defaultH2hAverageGoals: 2.1,
    formHistory: [70, 72, 74, 71, 70, 75, 76, 72, 74, 74],
    category: "national",
  },
  {
    id: "curacao",
    name: "Curaçao",
    shortName: "CUW",
    logo: "🇨🇼",
    color: "#1d4ed8", // Blue
    secondaryColor: "#facc15", // Yellow
    defaultAttackXg: 1.4,
    defaultDefenseXgConceded: 1.3,
    defaultForm: 68,
    defaultH2hAverageGoals: 2.3,
    formHistory: [60, 62, 65, 68, 70, 66, 64, 68, 70, 68],
    category: "national",
  },
  {
    id: "haiti",
    name: "Haiti",
    shortName: "HAI",
    logo: "🇭🇹",
    color: "#1d4ed8", // Blue
    secondaryColor: "#dc2626", // Red
    defaultAttackXg: 1.5,
    defaultDefenseXgConceded: 1.3,
    defaultForm: 71,
    defaultH2hAverageGoals: 2.4,
    formHistory: [65, 68, 70, 72, 70, 68, 74, 72, 70, 71],
    category: "national",
  },
  {
    id: "panama",
    name: "Panama",
    shortName: "PAN",
    logo: "🇵🇦",
    color: "#b91c1c", // Red
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.6,
    defaultDefenseXgConceded: 1.1,
    defaultForm: 74,
    defaultH2hAverageGoals: 2.5,
    formHistory: [70, 72, 75, 78, 74, 72, 76, 75, 72, 74],
    category: "national",
  },
  {
    id: "newzealand",
    name: "New Zealand",
    shortName: "NZL",
    logo: "🇳🇿",
    color: "#111827", // Black
    secondaryColor: "#ffffff",
    defaultAttackXg: 1.4,
    defaultDefenseXgConceded: 1.2,
    defaultForm: 70,
    defaultH2hAverageGoals: 2.2,
    formHistory: [65, 68, 70, 72, 68, 65, 70, 73, 72, 70],
    category: "national",
  },
];
